#argocd with helm
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app-helm-updater
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: yousif101/argocdproj:~v0.4
    argocd-image-updater.argoproj.io/write-back-method: git #added this 
  finalizers:
    - resources-finalizer.argocd.argoproj.io #without adding this it will not delete the pods when the appication is deleted
spec:
  project: default
  source:
    repoURL: https://github.com/yousif609230/argocd-proj.git
    targetRevision: main
    #path: environments/staging/my-app
    path: my-app-chart
    helm:
      parameters:
        - name: "replicaCount"
          value: "2"
        - name: "image.repository"
          value: "yousif101/argocdproj" 
        - name: "image.tag"
          value: "v0.1.0"
  destination:
    server: https://kubernetes.default.svc 
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true 
      allowEmpty: false 
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - validate=true
      - pruneLast=true


