apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io #without adding this it will not delete the pods when the appication is deleted
spec:
  project: default
  source:
    repoURL: https://github.com/yousif609230/argocd-prod.git
    targetRevision: main
    path: envs/dev
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true 
      allowEmpty: false 
    syncOptions:
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - validate=true
      - pruneLast=true